# Welcome to the OpenNMS Documentation

IMPORTANT: We are migrating our docs to the https://antora.org[Antora framework].
           This location is work in progress and not complete.
           For the official OpenNMS documentation, please go to https://docs.opennms.org.
           Feel free to contact us in our https://chat.opennms.com/opennms/channels/wtd[Chat] if you have questions.

OpenNMS is a scalable and highly configurable network management platform with comprehensive fault, performance, and traffic monitoring. 
It easily integrates with your core business applications and workflows to monitor and visualize everything in your network.

This documentation includes information on the following products:

* OpenNMS {distribution}
** Core (server that drives {distribution})
** Minion (for application perspective monitoring)
** Sentinel (for scalability) 
* Helm (for customized dashboards)
* Architecture for Learning Enabled Correlation (ALEC) (for alarm triage)
* Provisioning Integration Server (PRIS) (for integrating extracted data)

== Audience
This guide is suitable for administrative users and those who will use {page-component-title} to monitor their network.    

[[conventions]]
== Typographical Conventions

This guide uses the following typographical conventions:

[cols="25h,~"]
|===

|*Convention* |*Meaning*
|*bold* | Indicates UI elements to click or select in a procedure, and the names of UI elements like dialogs or icons. 
|_italics_| Introduces a defined or special word. Also used for the titles of publications.
|`code` | Anything you must type or enter, and the names for code-related elements (classes, methods, commands). 

|===

[[ga-admin-help]]
== Need Help?

* join the https://chat.opennms.com/opennms/channels/opennms-discussion[OpenNMS Discussion] chat
* join our community on https://opennms.discourse.group/latest[Discourse]
* contact sales@opennms.com to purchase https://www.opennms.com/support/[customer support]

== Legal Notice
include::legal-notice.adoc[]