---
version: 2.1

executors:
  docs-executor:
    docker:
      - image: opennms/antora:3.1.1-b9148
  publish-executor:
    docker:
      - image: circleci/buildpack-deps:focal
jobs:
  build-docs:
    executor: docs-executor
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Prepare Node environment
          command: |
            npm install
      - run:
          name: Generate HTML output for documentation
          no_output_timeout: 30m
          command: |
            sed -i -e "s,GITHUB_PRIME_TOKEN,${GITHUB_PRIME_TOKEN}," antora-playbook.yml
            DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr npx antora --stacktrace generate antora-playbook.yml
            ./link-latest.sh
            find public ! -type d -ls | awk '{ print $NF, $0 }' | sort | cut -d' ' -f 2- > build/public-filelist.txt
      - store_artifacts:
          path: build/site.zip
          destination: site.zip
      - store_artifacts:
          path: build/public-filelist.txt
          destination: public-filelist.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/public
            - project/build
  publish-docs:
    circleci_ip_ranges: true
    executor: publish-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "22:19:4a:22:07:4f:c1:0d:f3:fd:47:80:fb:9f:29:04"
      - attach_workspace:
          at: ~/
      - run:
          name: Install rsync dependency
          command: |
            sudo apt-get update
            sudo apt-get -y install rsync
      - run:
          name: Add SSH server fingerprint
          command: |
            echo 'web03.opennms.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPjI6KGxejlMooBADWlnhAq0HhcvSQDcJMfSgF3eRrDc29gWyzl8ET6WGPDpaw8XTnUNuVQmXW8G14Zs25CbDEE=' >> ~/.ssh/known_hosts
      - run:
          name: Push content to the web server
          command: |
            rsync -a --delete -e ssh public/ circleci@web03.opennms.com:/var/www/docs.opennms.com/htdocs

workflows:
  # Triggered by every commit to this repository
  commit:
    jobs:
      - build-docs
      - publish-docs:
          requires:
            - build-docs
          filters:
            branches:
              only:
                - master

  # Build and publish docs from master every night
  nightly:
    triggers:
      - schedule:
          cron: "42 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-docs
      - publish-docs:
          requires:
            - build-docs
